#!/bin/bash

# List of domains to check
domains=(
# "https://admin-pms.insurancedekho.com"
# "https://admin-pmsstaging.insurancedekho.com"
# "https://adminbrokerage.insurancedekho.com"
# "https://adminbrokeragestaging.insurancedekho.com"
# "https://adminbrokerageuat.insurancedekho.com"
# "https://adminbrokeragev2.insurancedekho.com"
# "https://adminbrokeragev2staging.insurancedekho.com"
# "https://adminbrokeragev2uat.insurancedekho.com"
# "https://ai.insurancedekho.com"
# "https://airflow-stage.insurancedekho.com"
# "https://airflow.insurancedekho.com"
# "https://allocation.insurancedekho.com"
# "https://allocationuat.insurancedekho.com"
# "https://analyticscommonreaderstaging.insurancedekho.com"
# "https://apiallocation.insurancedekho.com"
# "https://apiallocationstage.insurancedekho.com"
# "https://apibrkgnonmotor.insurancedekho.com"
# "https://apibrkgnonmotorstaging.insurancedekho.com"
# "https://apibrkgnonmotoruat.insurancedekho.com"
# "https://apibrokerageadminbff.insurancedekho.com"
# "https://apibrokerageadminbffstaging.insurancedekho.com"
"https://apibrokeragepartnership.insurancedekho.com"
# "https://apibrokeragerequotes.insurancedekho.com"
# "https://apibrokeragerequotesstaging.insurancedekho.com"
# "https://apicampaignstaging.insurancedekho.com"
# "https://apicentralservices.insurancedekho.com"
"https://apicentralservicespartnership.insurancedekho.com"
# "https://apicentralservicesstaging.insurancedekho.com"
# "https://apichatbotstaging.insurancedekho.com"
# "https://apiclaims.insurancedekho.com"
# "https://apiclaimsstaging.insurancedekho.com"
# "https://apiclaimsuat.insurancedekho.com"
# "https://apicoreops.insurancedekho.com"
"https://apicoreopspartnership.insurancedekho.com"
# "https://apicoreopsuat.insurancedekho.com"
# "https://apicps.insurancedekho.com"
"https://apicpsconsumerpartnership.insurancedekho.com"
# "https://apicpsdev.insurancedekho.com"
"https://apicpspartnership.insurancedekho.com"
# "https://apicpsstaging.insurancedekho.com"
# "https://apicpsuat.insurancedekho.com"
# "https://apiendorsement.insurancedekho.com"
# "https://apiendorsementstaging.insurancedekho.com"
# "https://apiendorsementuat.insurancedekho.com"
# "https://apifusion.insurancedekho.com"
# "https://apifusionstaging.insurancedekho.com"
# "https://apigateway.insurancedekho.com"
# "https://apigatewayb2bstaging.insurancedekho.com"
# "https://apigatewayb2buat.insurancedekho.com"
# "https://apigatewayb2c.insurancedekho.com"
# "https://apigatewayb2cstaging.insurancedekho.com"
# "https://apigatewaydev.insurancedekho.com"
"https://apigatewaypartnership.insurancedekho.com"
# "https://apigatewaystaging.insurancedekho.com"
# # "https://apigatewayuat.insurancedekho.com"
# "https://apiimagereader.insurancedekho.com"
# "https://apiimagereader2.insurancedekho.com"
# "https://apiimagereaderstaging.insurancedekho.com"
# "https://apiimagereaderstaging2.insurancedekho.com"
# "https://apiinspolicytracker.insurancedekho.com"
# "https://apiinspolicytrackerstaging.insurancedekho.com"
# "https://apiitmsdev.insurancedekho.com"
# "https://apiitmsdevv2.insurancedekho.com"
"https://apiitmspartnership.insurancedekho.com"
# "https://apiitmspreprod.insurancedekho.com"
# "https://apiitmsstaging.insurancedekho.com"
# "https://apiitmsstagingv2.insurancedekho.com"
# "https://apiitmsuat.insurancedekho.com"
# "https://apiitmsuatv2.insurancedekho.com"
# "https://apiitmsv2.insurancedekho.com"
"https://apiitmsv2partnership.insurancedekho.com"
# "https://apileads.insurancedekho.com"
"https://apileadspartnership.insurancedekho.com"
# "https://apileadsstaging.insurancedekho.com"
# "https://apileadsstaging2.insurancedekho.com"
# "https://apileadsuat.insurancedekho.com"
# "https://apilmspreprod.insurancedekho.com"
# "https://apilmsstaging.insurancedekho.com"
# "https://apimiddlelayer.insurancedekho.com"
"https://apimiddlelayerpartnership.insurancedekho.com"
# "https://apimiddlelayerstaging.insurancedekho.com"
# "https://apimiddlelayeruat.insurancedekho.com"
# "https://apiondcpreprod.insurancedekho.com"
# "https://apiops.insurancedekho.com"
# "https://apiopsdev.insurancedekho.com"
# "https://apiopsstaging.insurancedekho.com"
# "https://apiopsuat.insurancedekho.com"
# "https://apipaymentsbfestaging.insurancedekho.com"
# "https://apipolicyreader.insurancedekho.com"
# "https://apipolicyreaderstaging.insurancedekho.com"
# "https://apiposbff.insurancedekho.com"
# "https://apiposbffdev.insurancedekho.com"
"https://apiposbffpartnership.insurancedekho.com"
# "https://apiposbffstaging.insurancedekho.com"
# "https://apiposdev.insurancedekho.com"
"https://apipospartnership.insurancedekho.com"
# "https://apipospreprod.insurancedekho.com"
# "https://apiposstaging.insurancedekho.com"
# "https://apiposstaging2.insurancedekho.com"
# "https://apiposuat.insurancedekho.com"
# "https://apiquotesbrokeragestaging.insurancedekho.com"
# "https://apiselfinspectionstaging.insurancedekho.com"
# "https://apisfa.insurancedekho.com"
# "https://apisfadev.insurancedekho.com"
"https://apisfapartnership.insurancedekho.com"
# "https://apisfaportal.insurancedekho.com"
# "https://apisfaportaldev.insurancedekho.com"
"https://apisfaportalpartnership.insurancedekho.com"
# "https://apisfaportalstaging.insurancedekho.com"
# "https://apisfaportaluat.insurancedekho.com"
# "https://apisfastaging.insurancedekho.com"
# "https://apisfauat.insurancedekho.com"
"https://apisupportpartnership.insurancedekho.com"
# "https://apisupportstaging-v2.insurancedekho.com"
# "https://apisupportstaging.insurancedekho.com"
# "https://apisupportuat.insurancedekho.com"
# "https://apiwallet.insurancedekho.com"
# "https://apiwalletstaging.insurancedekho.com"
# "https://argocdstaging.insurancedekho.com"
# "https://autodb-hack.insurancedekho.com"
# "https://autodb.insurancedekho.com"
"https://autodbpartnership.insurancedekho.com"
# "https://autodbstaging.insurancedekho.com"
# "https://b2capi1.insurancedekho.com"
# "https://b2capi2.insurancedekho.com"
# "https://b2capidev.insurancedekho.com"
# "https://b2capipreprod.insurancedekho.com"
# "https://b2capipreprod1.insurancedekho.com"
# "https://b2capipreprod2.insurancedekho.com"
# "https://b2capistaging.insurancedekho.com"
# "https://b2cbackend.insurancedekho.com"
# "https://b2cstrapistaging.insurancedekho.com"
# "https://backendstaging.insurancedekho.com"
# "https://bmsstaging.insurancedekho.com"
# "https://bookstack.insurancedekho.com"
# "https://bottest.insurancedekho.com"
"https://brokeragekycpartnership.insurancedekho.com"
"https://brokeragemasterpartnership.insurancedekho.com"
# "https://brokeragemasterstaging.insurancedekho.com"
# "https://brokeragemasteruat.insurancedekho.com"
# "https://calendarstaging.insurancedekho.com"
# "https://campaign.insurancedekho.com"
# "https://claims-support.insurancedekho.com"
# "https://claims.insurancedekho.com"
# "https://communication.insurancedekho.com"
# "https://communicationdev.insurancedekho.com"
"https://communicationpartnership.insurancedekho.com"
# "https://communicationstaging.insurancedekho.com"
# "https://confluence.insurancedekho.com"
# "https://corstest.insurancedekho.com"
# "https://costanalyzer.insurancedekho.com"
# "https://cubeapm.insurancedekho.com"
# "https://cubeapmstaging.insurancedekho.com"
# "https://cubeapmstagingsvc.insurancedekho.com"
# "https://cubejs.insurancedekho.com"
# "https://customerprofile.insurancedekho.com"
"https://customerprofilepartnership.insurancedekho.com"
# "https://customerprofilestaging.insurancedekho.com"
# "https://dashboard.insurancedekho.com"
# "https://dashboarddev.insurancedekho.com"
# "https://dashboardstaging.insurancedekho.com"
# "https://dataservice.insurancedekho.com"
# "https://dataservicestaging.insurancedekho.com"
# "https://dev.insurancedekho.com"
# "https://dev1.insurancedekho.com"
# "https://dev2.insurancedekho.com"
# "https://developers.insurancedekho.com"
# "https://devopstest.insurancedekho.com"
# "https://devopstestsocket.insurancedekho.com"
# "https://digisign.insurancedekho.com"
# "https://digisignstaging.insurancedekho.com"
# "https://docs.insurancedekho.com"
# "https://docsstaging.insurancedekho.com"
# "https://docsuat.insurancedekho.com"
"https://docsv2partnership.insurancedekho.com"
# "https://docsv2staging.insurancedekho.com"
# "https://documents.insurancedekho.com"
# "https://documentservicedev.insurancedekho.com"
"https://documentservicepartnership.insurancedekho.com"
# "https://documentservicestaging.insurancedekho.com"
# "https://documentsuat.insurancedekho.com"
# "https://drapipos.insurancedekho.com"
# "https://encryption.insurancedekho.com"
"https://encryptionpartnership.insurancedekho.com"
# "https://encryptionstaging.insurancedekho.com"
# "https://endorsement.insurancedekho.com"
# "https://endorsementstaging.insurancedekho.com"
# "https://endorsementuat.insurancedekho.com"
# "https://externalapi.insurancedekho.com"
# "https://externalapistage.insurancedekho.com"
# "https://feedback.insurancedekho.com"
# "https://feedbackapistaging.insurancedekho.com"
# "https://finservstaging.insurancedekho.com"
# "https://fisstaging.insurancedekho.com"
# "https://fraudmitigation.insurancedekho.com"
# "https://fraudmitigationdev.insurancedekho.com"
# "https://fraudmitigationstaging.insurancedekho.com"
# "https://gibpldialerapi.insurancedekho.com"
# "https://gibpldialerapistage.insurancedekho.com"
# "https://gibpllmsapi.insurancedekho.com"
# "https://gibpllmsapistage.insurancedekho.com"
# "https://gibpllmsapiuat.insurancedekho.com"
# "https://grafana-prod.insurancedekho.com"
# "https://grafana-stage.insurancedekho.com"
# "https://graylog-admin.insurancedekho.com"
# "https://graylog.insurancedekho.com"
# "https://haste.insurancedekho.com"
# "https://health.insurancedekho.com"
# "https://healthapidev.insurancedekho.com"
# "https://healthapifyntune.insurancedekho.com"
# "https://healthapistaging.insurancedekho.com"
# "https://healthapistaging2.insurancedekho.com"
# "https://healthapistaging3.insurancedekho.com"
# "https://healthapiuat.insurancedekho.com"
# "https://healthcrm.insurancedekho.com"
# "https://healthcrmdev.insurancedekho.com"
# "https://healthcrmstaging.insurancedekho.com"
# "https://healthcrmstaging2.insurancedekho.com"
# "https://healthcrmstaging3.insurancedekho.com"
# "https://healthcrmtest.insurancedekho.com"
# "https://healthcrmuat.insurancedekho.com"
# "https://healthleaddev.insurancedekho.com"
"https://healthleadpartnership.insurancedekho.com"
# "https://healthleadstage.insurancedekho.com"
# "https://healthlmsconfig.insurancedekho.com"
# "https://healthrkmongostaging.insurancedekho.com"
# "https://healthseocrm.insurancedekho.com"
# "https://healthseocrmstaging.insurancedekho.com"
# "https://healthstage.insurancedekho.com"
# "https://healthstagefyn.insurancedekho.com"
# "https://helpdesk-stage.insurancedekho.com"
# "https://helpdesk.insurancedekho.com"
# "https://hralthapitest.insurancedekho.com"
# "https://hralthcrmtest.insurancedekho.com"
# "https://iam.insurancedekho.com"
# "https://iamdev.insurancedekho.com"
"https://iampartnership.insurancedekho.com"
# "https://iamstaging.insurancedekho.com"
# "https://idpaymentsstaging.insurancedekho.com"
# "https://idtree.insurancedekho.com"
# "https://idtreedev.insurancedekho.com"
"https://idtreepartnership.insurancedekho.com"
# "https://idtreestaging.insurancedekho.com"
# "https://idverse.insurancedekho.com"
# "https://idverseadmin.insurancedekho.com"
# "https://idverseadminstaging.insurancedekho.com"
"https://idverseservicepartnership.insurancedekho.com"
# "https://idverseservicestaging.insurancedekho.com"
# "https://idversestaging.insurancedekho.com"
# "https://ifmuistaging.insurancedekho.com"
# "https://ifmuiuat.insurancedekho.com"
# "https://igateway.insurancedekho.com"
# "https://iibautomationstaging.insurancedekho.com"
# "https://ilms.insurancedekho.com"
# "https://ilmsstaging.insurancedekho.com"
# "https://ilmsuat.insurancedekho.com"
# "https://insmdb.insurancedekho.com"
# "https://inspection.insurancedekho.com"
# "https://insslavedb.insurancedekho.com"
# "https://invoice-dev.insurancedekho.com"
# "https://ipsdashboard.insurancedekho.com"
# "https://ipsdashboardstaging.insurancedekho.com"
# "https://ipsstaging.insurancedekho.com"
# "https://itmsdev.insurancedekho.com"
# "https://itmsnode.insurancedekho.com"
"https://itmsnodepartnership.insurancedekho.com"
"https://itmspartnership.insurancedekho.com"
# "https://itmspolicymanagement.insurancedekho.com"
# "https://itmspolicymanagementstaging.insurancedekho.com"
# "https://itmspreprod.insurancedekho.com"
# "https://itmsreportdev.insurancedekho.com"
"https://itmsreportpartnership.insurancedekho.com"
# "https://itmsreportstaging.insurancedekho.com"
# "https://itmsreportuat.insurancedekho.com"
# "https://itmsstaging.insurancedekho.com"
# "https://itmsuat.insurancedekho.com"
# "https://jasper.insurancedekho.com"
# "https://jasperphpmyadmin.insurancedekho.com"
# "https://jenkins-stage.insurancedekho.com"
# "https://jenkins-v1.insurancedekho.com"
# "https://jenkins.insurancedekho.com"
# "https://jenkinslackbot.insurancedekho.com"
# "https://jenkinsprod.insurancedekho.com"
# "https://jenkinstest.insurancedekho.com"
# "https://kafkamanagerstage.insurancedekho.com"
# "https://kialidev.insurancedekho.com"
# "https://kibana.insurancedekho.com"
# "https://kong.insurancedekho.com"
# "https://kongapi.insurancedekho.com"
"https://kongapipartnership.insurancedekho.com"
# "https://kongapistaging.insurancedekho.com"
# "https://kube-prometheus.insurancedekho.com"
# "https://kube-prometheus3.insurancedekho.com"
# "https://kube-staging-ifm-api.insurancedekho.com"
# "https://kyc.insurancedekho.com"
# "https://kycbrokerage.insurancedekho.com"
# "https://kycbrokeragestage.insurancedekho.com"
# "https://kycbrokerageuat.insurancedekho.com"
# "https://kycdev.insurancedekho.com"
# "https://kycstaging.insurancedekho.com"
# "https://kycuat.insurancedekho.com"
# "https://leadmiddleware-v1.insurancedekho.com"
"https://leadmiddlewarepartnership.insurancedekho.com"
# "https://leadmiddlewarepreprod.insurancedekho.com"
# "https://leadmiddlewarestaging.insurancedekho.com"
# "https://leadmiddlewarestaging2.insurancedekho.com"
# "https://lms.insurancedekho.com"
# "https://lms1.insurancedekho.com"
# "https://lmsapi.insurancedekho.com"
# "https://lmsapisocketstage.insurancedekho.com"
# "https://lmsapisocketuat.insurancedekho.com"
# "https://lmsapistage.insurancedekho.com"
# "https://lmsapiuat.insurancedekho.com"
# "https://lmspreprod.insurancedekho.com"
# "https://lmsstage.insurancedekho.com"
# "https://lmsstaging.insurancedekho.com"
# "https://lmsuat.insurancedekho.com"
# "https://masscomm.insurancedekho.com"
"https://masscommpartnership.insurancedekho.com"
# "https://masscommstaging.insurancedekho.com"
# "https://masterdatapreprod.insurancedekho.com"
# "https://masteruploader.insurancedekho.com"
# "https://masteruploaderstaging.insurancedekho.com"
# "https://meesho.insurancedekho.com"
# "https://melorrascrapper.insurancedekho.com"
# "https://melorrascrapperstaging.insurancedekho.com"
# "https://metabasestag.insurancedekho.com"
# "https://middleware.insurancedekho.com"
# "https://mitmsstaging.insurancedekho.com"
# "https://nagios.insurancedekho.com"
# "https://nagiosadmin.insurancedekho.com"
# "https://nagiosstaging.insurancedekho.com"
# "https://nifi-analytics-stage.insurancedekho.com"
# "https://nifi-analytics.insurancedekho.com"
# "https://nifi-itms.insurancedekho.com"
# "https://ondcstaging.insurancedekho.com"
# "https://ondcuipreprod.insurancedekho.com"
# "https://ondcuistaging.insurancedekho.com"
# "https://otp.insurancedekho.com"
# "https://otpstaging.insurancedekho.com"
# "https://partner.insurancedekho.com"
"https://partnerapi-partnership.insurancedekho.com"
# "https://partnerapi-staging.insurancedekho.com"
# "https://partnerapi.insurancedekho.com"
# "https://partnerintegrationbackendstaging.insurancedekho.com"
# "https://partnerlmsstaging.insurancedekho.com"
# "https://partnershipsfaui.insurancedekho.com"
"https://paymentpartnership.insurancedekho.com"
# "https://paymentstaging.insurancedekho.com"
# "https://paymentuat.insurancedekho.com"
# "https://phpmyadminhealth.insurancedekho.com"
# "https://phpmyadminstaging.insurancedekho.com"
# "https://pms.insurancedekho.com"
"https://pmspartnership.insurancedekho.com"
# "https://pmsstaging.insurancedekho.com"
# "https://posappdev.insurancedekho.com"
"https://posapppartnership.insurancedekho.com"
# "https://posappstaging.insurancedekho.com"
# "https://posappstaging2.insurancedekho.com"
# "https://posappuat.insurancedekho.com"
# "https://poscorebe.insurancedekho.com"
# "https://poscorebedev.insurancedekho.com"
"https://poscorebepartnership.insurancedekho.com"
# "https://poscorebestaging.insurancedekho.com"
# "https://poscoredev.insurancedekho.com"
"https://poscorepartnership.insurancedekho.com"
# "https://poscoreuat.insurancedekho.com"
# "https://poscoreui.insurancedekho.com"
"https://poscoreuipartnership.insurancedekho.com"
# "https://posdev.insurancedekho.com"
# "https://poshealthpreprod.insurancedekho.com"
# "https://poshealthstaging.insurancedekho.com"
# "https://poshealthuat.insurancedekho.com"
"https://poskycpartnership.insurancedekho.com"
"https://pospartnership.insurancedekho.com"
# "https://pospreprod.insurancedekho.com"
# "https://posstaging.insurancedekho.com"
# "https://posstaging2.insurancedekho.com"
# "https://posui.insurancedekho.com"
# "https://posuidev.insurancedekho.com"
"https://posuipartnership.insurancedekho.com"
# "https://posuistaging.insurancedekho.com"
# "https://posuiuat.insurancedekho.com"
# "https://posuserdev.insurancedekho.com"
# "https://prepod.insurancedekho.com"
# "https://preprod.insurancedekho.com"
# "https://preprod1.insurancedekho.com"
# "https://preprod2.insurancedekho.com"
# "https://preprod3.insurancedekho.com"
# "https://prometheus-prod.insurancedekho.com"
# "https://prometheus-stage.insurancedekho.com"
# "https://qaautomationstaging.insurancedekho.com"
# "https://quotedev.insurancedekho.com"
# "https://quotes.insurancedekho.com"
# "https://quotesending.insurancedekho.com"
# "https://quotesengine.insurancedekho.com"
"https://quotespartnership.insurancedekho.com"
# "https://quotespreprod.insurancedekho.com"
# "https://quotesstaging.insurancedekho.com"
# "https://quotesuat.insurancedekho.com"
# "https://reconstaging.insurancedekho.com"
# "https://redash.insurancedekho.com"
# "https://redashstag.insurancedekho.com"
# "https://renewalstaging.insurancedekho.com"
# "https://rmongo.insurancedekho.com"
# "https://rmongolog.insurancedekho.com"
# "https://rmongostaging.insurancedekho.com"
# "https://rmongostaginglog.insurancedekho.com"
# "https://rockmongo.insurancedekho.com"
# "https://rockmongostaging.insurancedekho.com"
# "https://scoringapi.insurancedekho.com"
# "https://scoringapistaging.insurancedekho.com"
# "https://seleniumgridstaging.insurancedekho.com"
# "https://selfinspectionstaging.insurancedekho.com"
# "https://selfinspectionuat.insurancedekho.com"
# "https://sentry.insurancedekho.com"
# "https://seoapi.insurancedekho.com"
# "https://seoapistaging.insurancedekho.com"
# "https://seocms.insurancedekho.com"
# "https://seocmsstaging.insurancedekho.com"
# "https://sfa.insurancedekho.com"
# "https://sfastaging.insurancedekho.com"
# "https://sfauat.insurancedekho.com"
# "https://smebusinesspreprod1.insurancedekho.com"
# "https://smebusinessstaging.insurancedekho.com"
# "https://sonardev.insurancedekho.com"
# "https://sonarqube.insurancedekho.com"
# "https://sonarstage.insurancedekho.com"
# "https://spartacus.insurancedekho.com"
# "https://spartacusstage.insurancedekho.com"
# "https://stagecloudshell.insurancedekho.com"
# "https://stagekube-prometheus.insurancedekho.com"
# "https://staging-ifm-api.insurancedekho.com"
# "https://staging.insurancedekho.com"
# "https://stagingcis.insurancedekho.com"
# "https://stagingifmapi.insurancedekho.com"
# "https://staticstaging.insurancedekho.com"
# "https://supportemail.insurancedekho.com"
# "https://supportemailstaging.insurancedekho.com"
"https://supportpartnership.insurancedekho.com"
# "https://supportstaging.insurancedekho.com"
# "https://supportuat.insurancedekho.com"
# "https://tcsdevtest.insurancedekho.com"
# "https://testapibrokerage.insurancedekho.com"
# "https://testapimiddleware.insurancedekho.com"
# "https://testapiwallet.insurancedekho.com"
# "https://testhealthmiddleware.insurancedekho.com"
# "https://testpos.insurancedekho.com"
# "https://testquotes.insurancedekho.com"
# "https://testquotesmiddleware.insurancedekho.com"
# "https://trackwizz.insurancedekho.com"
# "https://trackwizzstage.insurancedekho.com"
# "https://uat.insurancedekho.com"
# "https://uat1.insurancedekho.com"
# "https://uatcis.insurancedekho.com"
# "https://utility.insurancedekho.com"
# "https://utilitydev.insurancedekho.com"
"https://utilitypartnership.insurancedekho.com"
# "https://utilitystaging.insurancedekho.com"
# "https://utrstaging.insurancedekho.com"
# "https://utruat.insurancedekho.com"
# "https://vaccinationnotifierstaging.insurancedekho.com"
# "https://wazuh.insurancedekho.com"
# "https://wiremockstaging.insurancedekho.com"
# "https://zap.insurancedekho.com"
)

for domain in "${domains[@]}"; do
    curl -s -o /dev/null -w "$domain\t%{http_code}\n" "$domain"
done